apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skov-run
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/simcax/deploy-skov.run.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: skov-run-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
