apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.content.PersistentVolume.Name }}
  namespace: {{ .Values.namespace }}
  labels: 
    directory: {{ .Values.content.PersistentVolume.Name }}
spec:
  capacity: 
    storage: {{ .Values.content.PersistentVolume.capacity }}
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  nfs:
    server: {{ .Values.content.PersistentVolume.nfsServer.ip }}
    path: {{ .Values.content.PersistentVolume.path}}